= SWT DyoB-Backend API Handbuch
Vincent Nadoll <s3003870@ba-sachsen.de>;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
= Einleitung

Willkommen zur API-Dokumentation des SWT DyoB-Backends von Team7.

Mit der API können Katalogdaten und Bestellprozesse auf einfache und programmatische Weise mithilfe herkömmlicher
HTTP-Anfragen verwaltet werden. Die Endpoints sind intuitiv und leistungsstark, sodass problemlos Requests gemacht
werden können, um Informationen abzurufen oder Aktionen auszuführen.

Die API-Dokumentation beginnt mit einem allgemeinen Überblick über das implementierte Design und die implementierte
Technologie, gefolgt von Referenzinformationen zu bestimmten Endpunkten.

[[requests]]
== Anfragen

Jedes Tool, das HTTP beherrscht, kann mit der API kommunizieren, indem es einfach den richtigen URI anfordert. Anfragen
sollten unter Verwendung des HTTPS-Protokolls gestellt werden, damit der Verkehr verschlüsselt wird. Die Schnittstelle
reagiert je nach erforderlicher Aktion auf unterschiedliche Methoden.

Dieser Dienst versucht, bei der Verwendung von HTTP-Verben die Standard-HTTP- und REST-Konventionen so genau wie möglich
einzuhalten.

|===
| Verb | Verwendung

| `GET`
| Wird zum Abrufen einer Ressource verwendet. Die angeforderten Informationen werden als JSON-Objekt zurückgegeben.

Die vom JSON-Objekt definierten Attribute können verwendet werden, um zusätzliche Anforderungen zu bilden. Jede
Anfrage, die die `GET`-Methode verwendet, ist schreibgeschützt und wirkt sich nicht auf die abgefragten Objekte aus.

| `POST`
| Wird verwendet, um eine neue Ressource zu erstellen.

Der `POST`-Request enthält alle Attribute, die zum Erstellen eines neuen Objekts erforderlich sind.

| `PUT`
| Wird verwendet, um eine vorhandene Ressource zu aktualisieren, wenn sie gefunden wird. Wenn sie nicht gefunden wird,
gibt die Operation eine Antwort zurück, die angibt, dass das Objekt nicht gefunden wurde.
|===

[[http-statuses]]
== HTTP Status

Neben den HTTP-Methoden, auf welche die API reagiert, werden auch Standard-HTTP-Status einschließlich Fehlercodes
zurückgegeben. Im Falle eines Problems enthält der Status den Fehlercode, während der Hauptteil der Antwort
normalerweise zusätzliche Informationen zu dem aufgetretenen Problem enthält. Wird ein Status im 500er-Bereich
zurückgesendet, weist dies im Allgemeinen auf ein serverseitiges Problem hin. Dies bedeutet, dass der Dienst ein Problem
hat und die Anfrage derzeit nicht erfüllen kann.

Dieser Dienst versucht, die Standardkonventionen für HTTP und REST bei der Verwendung des HTTP-Statuscodes so genau wie
möglich einzuhalten.

|===
| Status Code | Bedeutung

| `200 OK`
| Der Request war erfolgreich.

| `400 Bad Request`
| Der Request (-Body) war fehlerhaft. Der Response Body enthält einen Fehler, der weitere Informationen bereitstellt.

| `404 Not Found`
| Die angeforderte Ressource existiert nicht.
|===

[[responses]]
== Antworten

Wenn ein Request erfolgreich ist, wird normalerweise ein Response Body in Form eines JSON-Objekts zurückgesendet.
Ausnahmen sind die Methoden `POST` und `DELETE`, bei denen der Response Body leer ist.

Handelt es sich bei der angeforderten Ressource um eine Kollektion, wird diese in einem Stammobjekt mit dem Schlüssel
`_embedded`  eingebettet. Somit ist der JSON Response Body immer valide.

[[resources]]
= Ressourcen

[[resources-catalog]]
== Produkt

Die Produktressource bietet eine Übersicht über alle Produkte, die aktuell im Katalog verfügbar sind.

Da der Katalog über die UI des Dienstes verwaltet wird, werden lediglich Anfragen zur Informationssammlung angeboten.

[[resources-product-index]]
=== Katalogindex

Um einen Index über alle Produktkategorien zu bekommen, wird ein `GET`-Request an `/api/v1/catalog/index` gesendet.

Die Response ist ein JSON-Objekt mit einer Zuordnung zwischen Produkttypen und Links, mit dem die Sammlung der
entsprechenden Kategorie angefordert werden kann.

include::{snippets}/catalog/index/response-fields.adoc[]

==== cURL Beispiel

include::{snippets}/catalog/index/curl-request.adoc[]

==== Response Header

include::{snippets}/catalog/index/response-headers.adoc[]

==== Response Body

include::{snippets}/catalog/index/response-body.adoc[]

[[resources-product-category]]
=== Auflistung nach Produktkategorie

Wie in <<resources-product-index,Katalogindex>> erläutert, werden alle Kategorien und deren Endpoint aufgelistet. Wird
dem entsprechenden Link gefolgt, sendet der Dienst eine nach Kategorie gefilterte Auflistung von Produkten zurück. Dabei
wird dem Endpoint die jeweilige Kategorie als Request Parameter übergeben.

Der <<resources-product-list,nachfolgende Abschnitt>> erläutert, wie der generelle Response Body aussehen wird.
Dabei kann der Anzahl der Felder abhängig von der angeforderten Kategorie variieren.

Beispielsweise wird die Kategorie "Label" das zusätzliche Feld `image` enthalten.

Für die Auflistung wird ein `GET`-Request an den `/api/v1/catalog?category=$PRODUCT_CATEGORY`-Endpoint gesendet.

==== Request Parameter

include::{snippets}/catalog/product/request-parameters.adoc[]

[[resources-product-list]]
=== Auflistung aller Produkte

Alle Produkte können unabhängig ihrer Kategorie aufgelistet werden. Dafür wird ein `GET`-Request and den Endpoint
`/api/v1/catalog` geschickt.

Die Antwort ist ein JSON-Objekt mit einem Schlüssel `_embedded`. Der Wert hierfür ist ein Array von Produktobjekten, von
denen jedes *mindestens* die folgenden Standardattribute eines Produkts enthält.

include::{snippets}/catalog/list/response-fields.adoc[]

==== cURL Beispiel

include::{snippets}/catalog/list/curl-request.adoc[]

==== Response Header

include::{snippets}/catalog/list/response-headers.adoc[]

==== Response Body

include::{snippets}/catalog/list/response-body.adoc[]

[[resource-product-retrieve]]
=== Abruf eines existierenden Produkts

Um ein bestimmtes Produkt abzurufen, wird ein `GET`-Request an `/api/v1/catalog/$PRODUCT_ID` gestellt.

Die Antwort ist ein JSON-Objekt, dessen Felder *mindestens* die folgenden Attribute enthält:

include::{snippets}/catalog/retrieve/response-fields.adoc[]

==== cURL Beispiel

include::{snippets}/catalog/retrieve/curl-request.adoc[]

==== Response Headers

include::{snippets}/catalog/retrieve/response-headers.adoc[]

==== Response Body

include::{snippets}/catalog/retrieve/response-body.adoc[]

[[resources-cart]]
== Warenkorb

Der Warenkorb ist eine Ressource, welche mittels eines Cookies `JSESSIONID` an eine HTTP Session gebunden wird. Jede
Aktion auf diese Ressource wird auf den gleichen Warenkorb ausgeführt, solange wie der ausgelieferte Session-Cookie an
den nächsten Request gehangen wird. Die Session läuft nach 30 Minuten ab.

[[resources-cart-retrieve]]
=== Aktueller Warenkorb

Der aktuelle Bestand des Warenkorbs kann über einem `GET`-Request an den Endpoint `/api/v1/cart` eingesehen werden.
Im Folgenden werden Beispiele gezeigt, in denen der Warenkorb bereits Artikel enthält. Diese besitzt initial keine
Artikel. Die Kollektion `items` ist also leer.

include::{snippets}/cart/retrieve/response-fields.adoc[]

==== cURL Beispiel

include::{snippets}/cart/retrieve/curl-request.adoc[]

==== Response Headers

include::{snippets}/cart/retrieve/response-headers.adoc[]

==== Response Body

include::{snippets}/cart/retrieve/response-body.adoc[]

[[resources-cart-item-add]]
=== Artikel hinzufügen

Um ein Produkt dem Warenkorb hinzuzufügen, wird ein `POST`-Request an den
`/api/v1/cart?product_id=$PRODUCT_ID`-Endpoint gestellt. Das mit der Produkt ID assozierte Produkt wird dem Warenkorb
hinzugefügt. Die Response enthält die folgenden Felder.

include::{snippets}/cart/add/response-fields.adoc[]

==== cURL Beispiel

include::{snippets}/cart/add/curl-request.adoc[]

==== Request Parameters

include::{snippets}/cart/add/request-parameters.adoc[]

==== Request Headers

include::{snippets}/cart/add/request-headers.adoc[]

==== Response Headers

include::{snippets}/cart/add/response-headers.adoc[]

==== Response Body

include::{snippets}/cart/add/response-body.adoc[]

[[resources-cart-checkout]]
=== Checkout

Die Überführung von Warenkorb in die Bestellung wird mit einem `POST`-Request an `/api/v1/cart/checkout?amount=$AMOUNT`
eingeleitet und aktuelle auch abgeschlossen. Der Request Parameter gibt dabei an, wie viele Einheiten pro am Warenkorb
befindlichen Artikel gekauft werden soll. Einen Bezahlprozess gibt es noch nicht.

Ist die Bestellung abgeschlossen, wird ein Report erzeugt, der aufzeigt, welche Artikel erfolgreich bestellt wurde.
Tritt dabei ein Fehler auf, spiegelt sich dieser in dem erzeugten Report wider.

include::{snippets}/cart/checkout/response-fields.adoc[]

==== cURL Beispiel

include::{snippets}/cart/checkout/curl-request.adoc[]

==== Request Parameters

include::{snippets}/cart/checkout/request-parameters.adoc[]

==== Request Headers

include::{snippets}/cart/checkout/request-headers.adoc[]

==== Response Headers

include::{snippets}/cart/checkout/response-headers.adoc[]

==== Response Body

include::{snippets}/cart/checkout/response-body.adoc[]


[[glossary]]
== Glossar

|===
| Begriff | Beschreibung

| Artikel
| Ein Artikel ist ein Produkt welches in irgendeiner Weise mit einer ganz- oder gebrochenzahligen Menge assoziiert ist.
|===
