name: Publish Docker Image and Deploy

on:
  workflow_run:
    workflows: [ "Java CI with Maven" ]
    branches: [ main ]
    types:
      - completed
  repository_dispatch:
    types: [ "ci_succeeded" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vinado/team7-dyob:latest
          cache-from: type=registry,ref=vinado/team7-dyob:latest
          cache-to: type=inline
      - name: Call deployment Webhook
        uses: wei/curl@v1
        with:
          args: -X POST ${{ secrets.DEPLOYMENT_CALLBACK_URL }}
